import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Button from "../components/Button";
import IdeaCard from "../components/IdeaCard";

const Home: NextPage = () => {
  const [idea, setIdea] = useState("");
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full px-4 mx-auto max-w-3xl flex flex-col items-center font-semibold">
        <h1 className="mt-12 text-2xl sm:text-4xl text-center sm:mt-20">
          🦄 Welcome, to builspace's idea board
        </h1>
        <p className="text-center text-lg mt-4 sm:mt-7">
          Buildspace Alumni can create ideas and vote or unvote them.
        </p>
        <p className="text-center text-sm mt-3 sm:mt-6">
          Since, this is a testnet get your test NFT here.
        </p>
        <Button className="text-sm mt-1 sm:mt-3 w-full max-w-[124px]">
          Mint 🌟
        </Button>

        <div className="mt-9 font-bold sm:mt-6 w-full">
          <div className="w-full flex items-center justify-between">
            <p className="text-base sm:text-xl">Ideas</p>
            <div className="flex text-xs sm:text-sm">
              <button className="font-bold mr-3">_sort</button>
              <button className="font-bold">_filter</button>
            </div>
          </div>
          <div className="w-full p-2 mt-1 border border-strokes rounded-lg sm:mt-3 flex items-center">
            <input
              value={idea}
              onChange={(e) => setIdea(e.target.value)}
              placeholder="Mint a idea"
              className="bg-transparent w-full border-none text-base placeholder:text-gray-300 font-semibold"
            />
            <Button className="text-sm w-full ml-2 max-w-[124px]">
              💡 Mint Idea
            </Button>
          </div>
          <div className="w-full mt-3">
            <IdeaCard
              ideator="0x40d5250D1ce81fdD1F0E0FB4F471E57AA0c1FaD3"
              dateCreated="23 rd April’22"
              downVotes={16100}
              upVotes={26100}
              idea="I am farza and I worked on self-driving cars so that's pretty cool right? Connect your Ethereum wallet and wave at me!"
            />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
